// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7J1C_hM7OijVdwgiUfxZmuOWqu1wPY-k',
    appId: '1:374741660385:web:4b39b7a3c1f07ecd36bda0',
    messagingSenderId: '374741660385',
    projectId: 'perratauth',
    authDomain: 'perratauth.firebaseapp.com',
    storageBucket: 'perratauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFuAVilVwpEUDhth8YkA9NWmnCzzdgByY',
    appId: '1:374741660385:android:2a58fd92d10d483936bda0',
    messagingSenderId: '374741660385',
    projectId: 'perratauth',
    storageBucket: 'perratauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBujRk6wn0lrPjSAdUa0oOtJfJWYfeo4ys',
    appId: '1:374741660385:ios:fc6d637d09a1845936bda0',
    messagingSenderId: '374741660385',
    projectId: 'perratauth',
    storageBucket: 'perratauth.appspot.com',
    iosBundleId: 'com.example.perRat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBujRk6wn0lrPjSAdUa0oOtJfJWYfeo4ys',
    appId: '1:374741660385:ios:50c3b84aa6b4ff0936bda0',
    messagingSenderId: '374741660385',
    projectId: 'perratauth',
    storageBucket: 'perratauth.appspot.com',
    iosBundleId: 'com.example.perRat.RunnerTests',
  );
}
